export enum UserRole {
  DJ = 'DJ',
  DANCER = 'DANCER',
  CUSTOMER = 'CUSTOMER',
}

export interface FollowUser {
  id: string; // ID của follow relationship
  userId: string; // ID thực của user trong hệ thống
  name: string;
  username: string;
  avatar: string;
  bio: string;
  role: UserRole;
  isFollowing: boolean;
  isFollower: boolean;
  mutualFollowers?: number;
}

export const mockFollowers: FollowUser[] = [
  {
    id: 'follow_1',
    userId: '2',
    name: 'DJ Minh Trí',
    username: '@djminhtri',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'House & Techno DJ | Resident DJ @ClubNeon',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 145,
  },
  {
    id: 'follow_2',
    userId: '3',
    name: 'Linh Chi',
    username: '@linhchi_dancer',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Professional Dancer | Choreographer 💃',
    role: UserRole.DANCER,
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 89,
  },
  {
    id: 'follow_3',
    userId: '4',
    name: 'DJ Alex Nguyen',
    username: '@djalex',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'EDM & Progressive House | Booking: djalex@music.com',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 267,
  },
  {
    id: 'follow_4',
    userId: '5',
    name: 'Thanh Tú',
    username: '@thanhtu',
    avatar: 'https://i.pravatar.cc/150?img=4',
    bio: 'Bar regular | Party lover 🍸🎉',
    role: UserRole.CUSTOMER,
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 23,
  },
  {
    id: 'follow_5',
    userId: '6',
    name: 'Maya Dance',
    username: '@maya_moves',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Contemporary & Hip-hop Dancer | Dance instructor',
    role: UserRole.DANCER,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 178,
  },
  {
    id: 'follow_6',
    userId: '7',
    name: 'Hoàng Anh',
    username: '@hoanganh_vip',
    avatar: 'https://i.pravatar.cc/150?img=6',
    bio: 'Club enthusiast | Nightlife lover 🌃',
    role: UserRole.CUSTOMER,
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 12,
  },
  {
    id: 'follow_7',
    userId: '8',
    name: 'DJ Phương',
    username: '@djphuong',
    avatar: 'https://i.pravatar.cc/150?img=7',
    bio: 'Deep House & Chill Vibes | Every Friday @SkyBar',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 234,
  },
  {
    id: 'follow_8',
    userId: '9',
    name: 'Khánh Linh',
    username: '@khanhlinh_dancer',
    avatar: 'https://i.pravatar.cc/150?img=8',
    bio: 'Pole Dancer | Fitness enthusiast 💪✨',
    role: UserRole.DANCER,
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 156,
  },
  {
    id: 'follow_9',
    userId: '10',
    name: 'Tuấn Anh',
    username: '@tuananh_party',
    avatar: 'https://i.pravatar.cc/150?img=11',
    bio: 'Party animal | Weekend warrior 🎊',
    role: UserRole.CUSTOMER,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 34,
  },
  {
    id: 'follow_10',
    userId: '11',
    name: 'Bảo Trâm',
    username: '@baotram_',
    avatar: 'https://i.pravatar.cc/150?img=10',
    bio: 'Cocktail lover | Music addict 🍹🎵',
    role: UserRole.CUSTOMER,
    isFollowing: false,
    isFollower: true,
    mutualFollowers: 18,
  },
];

export const mockFollowing: FollowUser[] = [
  {
    id: 'follow_11',
    userId: '2',
    name: 'DJ Minh Trí',
    username: '@djminhtri',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'House & Techno DJ | Resident DJ @ClubNeon',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 145,
  },
  {
    id: 'follow_12',
    userId: '3',
    name: 'Linh Chi',
    username: '@linhchi_dancer',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Professional Dancer | Choreographer 💃',
    role: UserRole.DANCER,
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 89,
  },
  {
    id: 'follow_13',
    userId: '4',
    name: 'DJ Alex Nguyen',
    username: '@djalex',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'EDM & Progressive House | Booking: djalex@music.com',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 267,
  },
  {
    id: 'follow_14',
    userId: '12',
    name: 'DJ Hùng Vũ',
    username: '@djhungvu',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Trance & Psytrance | Festival DJ 🎧⚡',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 198,
  },
  {
    id: 'follow_15',
    userId: '13',
    name: 'Thiên Kim',
    username: '@thienkim_dance',
    avatar: 'https://i.pravatar.cc/150?img=13',
    bio: 'Latin Dance | Salsa & Bachata instructor',
    role: UserRole.DANCER,
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 67,
  },
  {
    id: 'follow_16',
    userId: '5',
    name: 'Thanh Tú',
    username: '@thanhtu',
    avatar: 'https://i.pravatar.cc/150?img=4',
    bio: 'Bar regular | Party lover 🍸🎉',
    role: UserRole.CUSTOMER,
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 23,
  },
  {
    id: 'follow_17',
    userId: '6',
    name: 'Maya Dance',
    username: '@maya_moves',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Contemporary & Hip-hop Dancer | Dance instructor',
    role: UserRole.DANCER,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 178,
  },
  {
    id: 'follow_18',
    userId: '14',
    name: 'Minh Quân',
    username: '@minhquan_beats',
    avatar: 'https://i.pravatar.cc/150?img=14',
    bio: 'Music producer | Sound engineer 🎹🎚️',
    role: UserRole.CUSTOMER,
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 45,
  },
  {
    id: 'follow_19',
    userId: '8',
    name: 'DJ Phương',
    username: '@djphuong',
    avatar: 'https://i.pravatar.cc/150?img=7',
    bio: 'Deep House & Chill Vibes | Every Friday @SkyBar',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 234,
  },
  {
    id: 'follow_20',
    userId: '15',
    name: 'Ngọc Anh',
    username: '@ngocanh_gogo',
    avatar: 'https://i.pravatar.cc/150?img=15',
    bio: 'Go-go Dancer | Performance artist ✨🔥',
    role: UserRole.DANCER,
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 201,
  },
  {
    id: 'follow_21',
    userId: '10',
    name: 'Tuấn Anh',
    username: '@tuananh_party',
    avatar: 'https://i.pravatar.cc/150?img=11',
    bio: 'Party animal | Weekend warrior 🎊',
    role: UserRole.CUSTOMER,
    isFollowing: true,
    isFollower: true,
    mutualFollowers: 34,
  },
  {
    id: 'follow_22',
    userId: '16',
    name: 'DJ Luna',
    username: '@djluna',
    avatar: 'https://i.pravatar.cc/150?img=16',
    bio: 'Female DJ | R&B & Hip-hop 👑🎵',
    role: UserRole.DJ,
    isFollowing: true,
    isFollower: false,
    mutualFollowers: 312,
  },
];